get:
	rsync jarvis:~/.config/emacs/modules/email-accounts.el ~/.config/emacs/modules/email-accounts.el
	rsync jarvis:~/.config/emacs/modules/email-refile.el ~/.config/emacs/modules/email-refile.el
	rsync jarvis:~/.config/emacs/modules/refile.py ~/.config/emacs/modules/refile.py
	rsync -r jarvis:~/.config/emacs/modules/refile.d ~/.config/emacs/modules/
